---
# defaults file for shorewall

## this file is out of date and needs to be updated

shorewall_originals_root_path: '../ace_hosts_originals'

shorewall_config_files:

  zones:
    src: 'etc/shorewall/zones.j2'
    dest: '/etc/shorewall/zones'

  interfaces:
    src: 'etc/shorewall/interfaces.j2'
    dest: '/etc/shorewall/interfaces'

  policy:
    src: 'etc/shorewall/policy.j2'
    dest: '/etc/shorewall/policy'

  rules:
    src: 'etc/shorewall/rules.j2'
    dest: '/etc/shorewall/rules'

  shorewall.conf:
    src: 'etc/shorewall/shorewall.conf.j2'
    dest: '/etc/shorewall/shorewall.conf'

shorewall_masq_file:

  masq:
    src: 'etc/shorewall/masq.j2'
    dest: '/etc/shorewall/masq'


zones:

  - name: "fw"
    type: "firewall"

  - name: "net"
    type: "ipv4"

  - name: "lan"
    type: "ipv4"

  - name: "vpn"
    type: "ipv4"

interfaces: 

  - int: "eth0"
    zone: "net"
  
  - int: "eth1"
    zone: "lan"
  
  - int: "tun0"
    zone: "vpn"

policies:

  - src: "$FW"
    dst: "net"
    policy: "ACCEPT"

  - src: "net"
    dst: "$FW"
    policy: "DROP"
    log_level: "info"

#  - src: "net"
#    dst: "all"
#    policy: "DROP"
#    log_level: "info"

  - src: "lan"
    dst: "all"
    policy: "ACCEPT"

  - src: "vpn"
    dst: "all"
    policy: "ACCEPT"

rules:

- rules:

  - action: "ACCEPT"
    src: "0.0.0.0/0"
    dest: "$FW"    
    proto: "tcp"
    port: 22
    comment: "Public SSH"

  - action: "ACCEPT"
    src: "0.0.0.0/0"
    dest: "$FW"
    proto: "udp"
    port: 1194
    comment: "Public OpenVPN"

